[project]
name = "ball-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=4.10.0.84",
    "numpy>=2.1.0",
    "imutils>=0.5.4",
]
